from types import ModuleType
from typing import Iterator

from ..tests import OdooSuite
from .runner import OdooTestResult

def get_test_modules(module: str) -> list: ...
def _get_tests_modules(path: str, module: str) -> list: ...
def _get_upgrade_test_modules(module) -> Iterator[ModuleType]: ...
def make_suite(module_name: str, position: str = ...) -> OdooSuite: ...
def run_suite(suite: OdooSuite, module_name: str) -> OdooTestResult: ...
def unwrap_suite(test) -> Iterator: ...
