from importlib.machinery import ModuleSpec
from types import ModuleType
from typing import Iterator

from .result import OdooTestResult
from .suite import OdooSuite

def get_test_modules(module: str) -> list: ...
def _get_tests_modules(mod: ModuleSpec) -> list: ...
def _get_upgrade_test_modules(module) -> Iterator[ModuleType]: ...
def make_suite(module_names: list[str], position: str = ...) -> OdooSuite: ...
def run_suite(suite: OdooSuite, module_name: str | None = ...) -> OdooTestResult: ...
def unwrap_suite(test) -> Iterator: ...
