from typing import Any
from unittest import BaseTestSuite

__unittest: bool

class TestSuite(BaseTestSuite):
    def run(self, result, debug: bool = ...): ...
    def _handleClassSetUp(self, test, result) -> None: ...
    def _createClassOrModuleLevelException(
        self, result, exception, method_name, parent, info: Any | None = ...
    ) -> None: ...
    def _tearDownPreviousClass(self, test, result) -> None: ...

class _ErrorHolder:
    failureException: Any
    description: str
    def __init__(self, description: str) -> None: ...
    def id(self) -> str: ...
    def shortDescription(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def run(self, result) -> None: ...
    def __call__(self, result) -> None: ...
    def countTestCases(self) -> int: ...

class OdooSuite(TestSuite):
    def _handleClassSetUp(self, test, result) -> None: ...
    def _tearDownPreviousClass(self, test, result) -> None: ...
    def has_http_case(self) -> bool: ...
