from argparse import Namespace

BLACKLIST: set[str]
IGNORE: tuple[str, ...]
INSTALL_BLACKLIST: set[str]

def install(db_name: str, module_id: int, module_name: str) -> None: ...
def uninstall(db_name: str, module_id: int, module_name: str) -> None: ...
def cycle(db_name: str, module_id: int, module_name: str) -> None: ...
def parse_args() -> Namespace: ...
def test_full(args: Namespace) -> None: ...
def test_uninstall(args: Namespace) -> None: ...
def test_scripts(args: Namespace) -> None: ...
