from odoo.tests import BaseCase

class TestParseInlineTemplate(BaseCase):
    def test_no_expression(self) -> None: ...
    def test_expression1(self) -> None: ...
    def test_expression2(self) -> None: ...
