from argparse import Action, Namespace

BLACKLIST: set[str]
IGNORE: tuple[str, ...]
INSTALL_BLACKLIST: set[str]

def install(db_name: str, module_id: int, module_name: str) -> None: ...
def uninstall(db_name: str, module_id: int, module_name: str) -> None: ...
def cycle(db_name: str, module_id: int, module_name: str) -> None: ...
def parse_args() -> Namespace: ...

class UninstallAction(Action):
    def __call__(self, parser, namespace, values, option_string = ...) -> None: ...

class StandaloneAction(Action):
    def __call__(self, parser, namespace, values, option_string = ...) -> None: ...

def test_cycle(args: Namespace) -> None: ...
def test_uninstall(args: Namespace) -> None: ...
def test_standalone(args: Namespace) -> None: ...
