from typing import Any

_logger: Any
BLACKLIST: Any
IGNORE: Any

def install(db_name, module_id, module_name) -> None: ...
def uninstall(db_name, module_id, module_name) -> None: ...
def cycle(db_name, module_id, module_name) -> None: ...
def parse_args(): ...
def test_full(args): ...
def test_uninstall(args) -> None: ...
def test_scripts(args) -> None: ...
