from typing import Any

class odt2odt:
    localcontext: Any
    etree: Any
    def __init__(self, odt, localcontext) -> None: ...
    def render(self): ...

def parseNode(node, localcontext=...): ...
