from . import Command
from typing import Any, Optional

class Deploy(Command):
    session: Any = ...
    def __init__(self) -> None: ...
    def deploy_module(self, module_path: Any, url: Any, login: Any, password: Any, db: str = ..., force: bool = ...): ...
    def upload_module(self, server: Any, module_file: Any, force: bool = ..., csrf_token: Optional[Any] = ...): ...
    def authenticate(self, server: Any, login: Any, password: Any, db: str = ...): ...
    def zip_module(self, path: Any): ...
    def run(self, cmdargs: Any) -> None: ...
