from . import Command
from typing import Any

class Deploy(Command):
    session: Any
    def __init__(self) -> None: ...
    def deploy_module(self, module_path, url, login, password, db: str = ..., force: bool = ...): ...
    def login_upload_module(self, module_file, url, login, password, db, force: bool = ...): ...
    def zip_module(self, path): ...
    def run(self, cmdargs) -> None: ...
