from . import Command

class GenProxyToken(Command):
    command_name: str
    def __init__(self) -> None: ...
    def generate_token(self, length: int = ...): ...
    def run(self, cmdargs) -> None: ...
