from . import Command as Command
from typing import Any, Optional

class Scaffold(Command):
    def run(self, cmdargs: Any) -> None: ...
    def epilog(self): ...

builtins: Any

def snake(s: Any): ...
def pascal(s: Any): ...
def directory(p: Any, create: bool = ...): ...

env: Any

class template:
    id: Any = ...
    path: Any = ...
    def __init__(self, identifier: Any) -> None: ...
    def __str__(self): ...
    def files(self) -> None: ...
    def render_to(self, modname: Any, directory: Any, params: Optional[Any] = ...) -> None: ...

def die(message: Any, code: int = ...) -> None: ...
def warn(message: Any) -> None: ...
