from . import Command
from typing import Any

class Scaffold(Command):
    def run(self, cmdargs) -> None: ...
    def epilog(self): ...

builtins: Any

def snake(s): ...
def pascal(s): ...
def directory(p, create: bool = ...): ...

env: Any

class template:
    id: Any
    path: Any
    def __init__(self, identifier) -> None: ...
    def __str__(self): ...
    def files(self) -> None: ...
    def render_to(self, modname, directory, params: Any | None = ...) -> None: ...

def die(message, code: int = ...) -> None: ...
def warn(message) -> None: ...
