from . import Command
from typing import Any

__author__: Any
__version__: Any
_logger: Any

def check_root_user() -> None: ...
def check_postgres_user() -> None: ...
def report_configuration() -> None: ...
def rm_pid_file(main_pid) -> None: ...
def setup_pid_file() -> None: ...
def export_translation() -> None: ...
def import_translation() -> None: ...
def main(args) -> None: ...

class Server(Command):
    def run(self, args) -> None: ...
