import code
from . import Command as Command
from odoo.tools import config as config
from typing import Any, Optional

_logger: Any

def raise_keyboard_interrupt(*a: Any) -> None: ...

class Console(code.InteractiveConsole):
    def __init__(self, locals: Optional[Any] = ..., filename: str = ...) -> None: ...

class Shell(Command):
    supported_shells: Any = ...
    def init(self, args: Any) -> None: ...
    def console(self, local_vars: Any): ...
    def ipython(self, local_vars: Any) -> None: ...
    def ptpython(self, local_vars: Any) -> None: ...
    def bpython(self, local_vars: Any) -> None: ...
    def python(self, local_vars: Any) -> None: ...
    def shell(self, dbname: Any) -> None: ...
    def run(self, args: Any): ...
