import code
from . import Command
from typing import Any

_logger: Any

def raise_keyboard_interrupt(*a) -> None: ...

class Console(code.InteractiveConsole):
    def __init__(self, locals: Any | None = ..., filename: str = ...) -> None: ...

class Shell(Command):
    supported_shells: Any
    def init(self, args) -> None: ...
    def console(self, local_vars): ...
    def ipython(self, local_vars) -> None: ...
    def ptpython(self, local_vars) -> None: ...
    def bpython(self, local_vars) -> None: ...
    def python(self, local_vars) -> None: ...
    def shell(self, dbname) -> None: ...
    def run(self, args): ...
