from . import Command
from typing import Any

class Start(Command):
    def get_module_list(self, path: Any): ...
    def run(self, cmdargs: Any): ...

def die(message: Any, code: int = ...) -> None: ...
