# Stubs for odoo.cli.start (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from . import Command


class Start(Command):
    def get_module_list(self, path: Any): ...
    def run(self, cmdargs: Any): ...

def die(message: Any, code: int = ...) -> None: ...
