from . import Command

class TSConfig(Command):
    command_name: str
    def __init__(self) -> None: ...
    def get_module_list(self, path): ...
    def clean_path(self, path): ...
    def prefix_suffix_path(self, path, prefix, suffix): ...
    def remove_(self, modules, module) -> None: ...
    def run(self, cmdargs) -> None: ...
    def generate_imports(self, modules): ...
    def generate_file_content(self, modules, paths): ...
    def generate_excludes(self): ...
