from typing import Any, Optional

_logger: Any

class Graph(dict):
    def add_node(self, name, info): ...
    def update_from_db(self, cr) -> None: ...
    def add_module(self, cr, module, force: Optional[Any] = ...) -> None: ...
    def add_modules(self, cr, module_list, force: Optional[Any] = ...): ...
    def __iter__(self) -> Any: ...
    def __str__(self): ...

class Node:
    def __new__(cls, name, graph, info): ...
    name: Any
    graph: Any
    info: Any
    children: Any
    depth: int
    def __init__(self, name, graph, info) -> None: ...
    @property
    def data(self): ...
    def add_child(self, name, info): ...
    def __setattr__(self, name, value) -> None: ...
    def __iter__(self) -> Any: ...
    def __str__(self): ...
    def _pprint(self, depth: int = ...): ...
