from odoo.modules.module import get_resource_path as get_resource_path
from odoo.tools import pycompat as pycompat
from odoo.tools.parse_version import parse_version as parse_version
from typing import Any

def load_script(path: Any, module_name: Any): ...

_logger: Any

class MigrationManager:
    cr: Any = ...
    graph: Any = ...
    migrations: Any = ...
    def __init__(self, cr: Any, graph: Any) -> None: ...
    def _get_files(self): ...
    def migrate_module(self, pkg: Any, stage: Any): ...
