from typing import Any, Optional

MANIFEST_NAMES: Any
README: Any
_logger: Any

def ad_paths(): ...

loaded: Any

class AddonsHook:
    def find_module(self, name: Any, path: Optional[Any] = ...): ...
    def load_module(self, name: Any): ...

class OdooHook:
    def find_module(self, name: Any, path: Optional[Any] = ...): ...
    def load_module(self, name: Any): ...

def initialize_sys_path() -> None: ...
def get_module_path(module: Any, downloaded: bool = ..., display_warning: bool = ...): ...
def get_module_filetree(module: Any, dir: str = ...): ...
def get_resource_path(module: Any, *args: Any): ...
def check_resource_path(mod_path: Any, *args: Any): ...
get_module_resource = get_resource_path

def get_resource_from_path(path: Any): ...
def get_module_icon(module: Any): ...
def module_manifest(path: Any): ...
def get_module_root(path: Any): ...
def load_information_from_description_file(module: Any, mod_path: Optional[Any] = ...): ...
def load_openerp_module(module_name: Any) -> None: ...
def get_modules(): ...
def get_modules_with_version(): ...
def adapt_version(version: Any): ...

current_test: Any
