from typing import Any

to_19_fr: Any
tens_fr: Any
denom_fr: Any

def _convert_nn_fr(val): ...
def _convert_nnn_fr(val): ...
def french_number(val): ...
def amount_to_text_fr(number, currency): ...

to_19_nl: Any
tens_nl: Any
denom_nl: Any

def _convert_nn_nl(val): ...
def _convert_nnn_nl(val): ...
def dutch_number(val): ...
def amount_to_text_nl(number, currency): ...

_translate_funcs: Any

def add_amount_to_text_function(lang, func) -> None: ...
def amount_to_text(nbr, lang: str = ..., currency: str = ...): ...
