class assertion_report:
    successes: int = ...
    failures: int = ...
    def __init__(self) -> None: ...
    def record_success(self) -> None: ...
    def record_failure(self) -> None: ...
    def record_result(self, result) -> None: ...
    def __str__(self) -> str: ...
