from typing import Any, Optional

VERSION: int
DEFAULT_EXCLUDE: Any
STANDARD_MODULES: Any
MAX_FILE_SIZE: Any

class Cloc:
    modules: Any = ...
    code: Any = ...
    total: Any = ...
    errors: Any = ...
    max_width: int = ...
    def __init__(self) -> None: ...
    def parse_xml(self, s: Any): ...
    def parse_py(self, s: Any): ...
    def parse_js(self, s: Any): ...
    def book(self, module: Any, item: str = ..., count: Any = ...) -> None: ...
    def count_path(self, path: Any, exclude: Optional[Any] = ...) -> None: ...
    def count_modules(self, env: Any) -> None: ...
    def count_customization(self, env: Any) -> None: ...
    def count_env(self, env: Any) -> None: ...
    def count_database(self, database: Any) -> None: ...
    def report(self, verbose: bool = ..., width: Optional[Any] = ...): ...
