import datetime
from dateutil.relativedelta import relativedelta

from typing import Tuple, Iterator, TypeVar

_T = TypeVar('_T', datetime.date, datetime.datetime)


def get_month(date: _T) -> Tuple[_T, _T]: ...
def get_quarter_number(date) -> int: ...
def get_quarter(date: _T) -> Tuple[_T, _T]: ...
def get_fiscal_year(date: _T, day: int = ..., month: int = ...) -> Tuple[_T, _T]: ...
def get_timedelta(qty, granularity) -> relativedelta: ...
def start_of(value: _T, granularity) -> _T: ...
def end_of(value: _T, granularity) -> _T: ...
def add(value: _T, *args, **kwargs) -> _T: ...
def subtract(value: _T, *args, **kwargs) -> _T: ...
def json_default(obj) -> str: ...
def date_range(start: datetime.datetime, end: datetime.datetime, step: relativedelta = ...) -> Iterator[datetime.datetime]: ...
