# Stubs for odoo.tools.debugger (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SUPPORTED_DEBUGGER: Any

def post_mortem(config: Any, info: Any) -> None: ...
