from typing import Any

def _float_check_precision(
    precision_digits: Any | None = ..., precision_rounding: Any | None = ...
): ...
def float_round(
    value,
    precision_digits: Any | None = ...,
    precision_rounding: Any | None = ...,
    rounding_method: str = ...,
): ...
def float_is_zero(
    value, precision_digits: Any | None = ..., precision_rounding: Any | None = ...
): ...
def float_compare(
    value1,
    value2,
    precision_digits: Any | None = ...,
    precision_rounding: Any | None = ...,
): ...
def float_repr(value, precision_digits): ...

_float_repr = float_repr

class float_precision(float):
    def __new__(cls, value, precision_digits): ...
    def float_repr(self): ...
