class GeoIPResolver:
    fname: str
    version: int
    def __init__(self, fname: str) -> None: ...
    def __del__(self) -> None: ...
    @classmethod
    def open(cls, fname: str) -> GeoIPResolver | None: ...
    def resolve(self, ip: str) -> dict: ...
    def record_by_addr(self, addr: str) -> dict: ...
