from typing import Any, Optional

__all__: Any

class LRU:
    _lock: Any = ...
    count: Any = ...
    d: Any = ...
    def __init__(self, count: Any, pairs: Any = ...) -> None: ...
    def __contains__(self, obj: Any): ...
    def get(self, obj: Any, val: Optional[Any] = ...): ...
    def __getitem__(self, obj: Any): ...
    def __setitem__(self, obj: Any, val: Any) -> None: ...
    def __delitem__(self, obj: Any) -> None: ...
    def __len__(self): ...
    def pop(self, key: Any): ...
    def clear(self) -> None: ...
