# Stubs for odoo.tools.mimetypes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple
from typing import Any

_Entry = namedtuple('_Entry', ['mimetype', 'signatures', 'discriminants'])

def guess_mimetype(bin_data: Any, default: str = ...): ...

guess_mimetype: Any
