# Stubs for odoo.tools.parse_version (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

component_re: Any
replace: Any

def parse_version(s: Any): ...
