HEAD: str
TAIL: str

def output_field(f): ...
def extract_keys(lines): ...
def write_field(out, key, value) -> None: ...
def write_fields(out, fields) -> None: ...
def extract_keys_from_pdf(filename): ...
def fill_pdf(infile, outfile, fields) -> None: ...
def testfill_pdf(infile, outfile) -> None: ...
