from odoo.tools import pycompat as pycompat
from typing import Any

def Random(seed): ...
def format_str(val, counter, values): ...
def chain_factories(field_factories, model_name): ...
def root_factory() -> None: ...
def randomize(vals, weights: Any | None = ..., seed: bool = ..., formatter=..., counter_offset: int = ...): ...
def cartesian(vals, weights: Any | None = ..., seed: bool = ..., formatter=..., then: Any | None = ...): ...
def iterate(vals, weights: Any | None = ..., seed: bool = ..., formatter=..., then: Any | None = ...): ...
def constant(val, formatter=...): ...
def compute(function, seed: Any | None = ...): ...
def randint(a, b, seed: Any | None = ...): ...
def randfloat(a, b, seed: Any | None = ...): ...
def randdatetime(*, base_date: Any | None = ..., relative_before: Any | None = ..., relative_after: Any | None = ..., seed: Any | None = ...): ...
