from typing import Any, Optional

PY2: Any

def to_native(source, encoding: str = ..., falsy_empty: bool = ...): ...

integer_types: Any

def implements_to_string(cls): ...
def implements_iterator(cls): ...
def csv_reader(stream, **params) -> None: ...
def csv_writer(stream, **params): ...

unichr = chr
text_type = str
imap = map
izip = zip
ifilter = filter

def reraise(tp, value, tb: Optional[Any] = ...) -> None: ...
def to_text(source): ...
