from re import Pattern
from typing import Iterable, Iterator

from ..sql_db import Cursor

IDENT_RE: Pattern

class Query:
    order: str | None
    limit: int | None
    offset: int | None
    def __init__(self, cr: Cursor, alias: str, table: str | None = ...) -> None: ...
    def add_table(self, alias: str, table: str | None = ...) -> None: ...
    def add_where(self, where_clause: str, where_params: Iterable = ...) -> None: ...
    def join(
        self,
        lhs_alias: str,
        lhs_column: str,
        rhs_table: str,
        rhs_column: str,
        link: str,
        extra: str | None = ...,
        extra_params: tuple = ...,
    ) -> str: ...
    def left_join(
        self,
        lhs_alias: str,
        lhs_column: str,
        rhs_table: str,
        rhs_column: str,
        link: str,
        extra: str | None = ...,
        extra_params: tuple = ...,
    ) -> str: ...
    def select(self, *args) -> tuple[str, list]: ...
    def subselect(self, *args) -> tuple[str, list]: ...
    def is_empty(self) -> bool: ...
    def get_sql(self) -> tuple[str, str, list]: ...
    def get_result_ids(self) -> tuple[int, ...]: ...
    def set_result_ids(self, ids, ordered: bool = ...) -> None: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    @property
    def where_clause(self) -> tuple[str, ...]: ...
    @property
    def where_clause_params(self) -> tuple: ...
