from typing import Any

INLINE_TEMPLATE_REGEX: Any

def relativedelta_proxy(*args, **kwargs): ...

template_env_globals: Any

def parse_inline_template(text): ...
def convert_inline_template_to_qweb(template): ...
def render_inline_template(template_instructions, variables): ...
