from typing import Any

shortener: Any
shorten: Any

class Speedscope:
    init_stack_trace: Any
    init_stack_trace_level: Any
    caller_frame: Any
    init_caller_frame: Any
    profiles_raw: Any
    name: Any
    frames_indexes: Any
    frame_count: int
    profiles: Any
    def __init__(self, name: str = ..., init_stack_trace: Any | None = ...) -> None: ...
    def add(self, key, profile) -> None: ...
    def convert_stack(self, stack) -> None: ...
    def add_output(self, names, complete: bool = ..., display_name: Any | None = ..., use_context: bool = ..., **params): ...
    def add_default(self): ...
    def make(self): ...
    def get_frame_id(self, frame): ...
    def stack_to_ids(self, stack, context, stack_offset: int = ...): ...
    def process(self, entries, continuous: bool = ..., hide_gaps: bool = ..., use_context: bool = ...): ...
