from typing import Any

_logger: Any

def add_text_before(node: Any, text: Any) -> None: ...
def add_text_inside(node: Any, text: Any) -> None: ...
def remove_element(node: Any) -> None: ...
def locate_node(arch: Any, spec: Any): ...
def apply_inheritance_specs(source: Any, specs_tree: Any, inherit_branding: bool = ..., pre_locate: Any = ...): ...
