from typing import Any

_logger: Any
_validators: Any
_relaxng_cache: Any
READONLY: Any

def _get_attrs_symbols(): ...
def get_variable_names(expr: Any): ...
def get_dict_asts(expr: Any): ...
def _check(condition: Any, explanation: Any) -> None: ...
def get_domain_identifiers(expr: Any): ...
def valid_view(arch: Any, **kwargs: Any): ...
def validate(*view_types: Any): ...
def relaxng(view_type: Any): ...
def schema_valid(arch: Any, **kwargs: Any): ...
