from ast import expr as _expr
from re import Pattern
from typing import Callable, TypeVar

from lxml.etree import RelaxNG, _Element

_CallableT = TypeVar("_CallableT", bound=Callable)

READONLY: Pattern

def get_variable_names(expr: str | _expr) -> set[str]: ...
def get_dict_asts(expr: str | _expr) -> dict: ...
def get_domain_identifiers(expr: str | _expr) -> tuple[set[str], set[str]]: ...
def valid_view(arch: _Element, **kwargs) -> bool: ...
def validate(*view_types: str) -> Callable[[_CallableT], _CallableT]: ...
def relaxng(view_type: str) -> RelaxNG: ...
def schema_valid(arch: _Element, **kwargs) -> bool: ...
