from lxml import etree
from typing import Any, Optional

class odoo_resolver(etree.Resolver):
    env: Any = ...
    def __init__(self, env: Any) -> None: ...
    def resolve(self, url: Any, id: Any, context: Any): ...

def _check_with_xsd(tree_or_str: Any, stream: Any, env: Optional[Any] = ...) -> None: ...
def create_xml_node_chain(first_parent_node: Any, nodes_list: Any, last_node_value: Optional[Any] = ...): ...
def create_xml_node(parent_node: Any, node_name: Any, node_value: Optional[Any] = ...): ...
