from lxml import etree
from typing import Any

class odoo_resolver(etree.Resolver):
    env: Any
    def __init__(self, env) -> None: ...
    def resolve(self, url, id, context): ...

def _check_with_xsd(tree_or_str, stream, env: Any | None = ...) -> None: ...
def create_xml_node_chain(first_parent_node, nodes_list, last_node_value: Any | None = ...): ...
def create_xml_node(parent_node, node_name, node_value: Any | None = ...): ...
