from typing import Any, Optional

from odoo.tools.misc import file_open as file_open

def check_with_xsd(tree_or_str, stream) -> None: ...
def _check_with_xsd(tree_or_str, stream) -> None: ...
def create_xml_node_chain(
    first_parent_node, nodes_list, last_node_value: Optional[Any] = ...
): ...
def create_xml_node(parent_node, node_name, node_value: Optional[Any] = ...): ...
