# Stubs for odoo (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

__path__: Any
evented: bool

def gevent_wait_callback(conn: Any, timeout: Optional[Any] = ...) -> None: ...

multi_process: bool
SUPERUSER_ID: int

def registry(database_name: Optional[Any] = ...): ...

from . import (addons, exceptions, conf, loglevels, modules, netsvc, osv, release,
               service, sql_db, tools, models, fields, api, cli, http)
from .tools.translate import _ as _
