# Stubs for odoo (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

__path__: Any
evented: bool

def gevent_wait_callback(conn: Any, timeout: Optional[Any] = ...) -> None: ...

multi_process: bool
SUPERUSER_ID: int

def registry(database_name: Optional[Any] = ...): ...

from . import addons
from . import conf
from . import loglevels
from . import modules
from . import netsvc
from . import osv
from . import release
from . import service
from . import sql_db
from . import tools
from . import models
from . import fields
from . import api
from . import cli
from . import http
from .tools.translate import _ as _
