import datetime

from dateutil.relativedelta import relativedelta as relativedelta
from typing import Any, Optional

DATE_LENGTH: Any
DATETIME_LENGTH: Any
EMPTY_DICT: Any
RENAMED_ATTRS: Any
_logger: Any
_schema: Any
Default: Any

def copy_cache(records: Any, env: Any) -> None: ...
def first(records: Any): ...
def resolve_mro(model: Any, name: Any, predicate: Any): ...

class MetaField(type):
    by_type: Any = ...
    def __new__(meta: Any, name: Any, bases: Any, attrs: Any): ...
    def __init__(cls, name: Any, bases: Any, attrs: Any) -> None: ...

_global_seq: Any

class Field(MetaField('DummyField', (object,), {})):
    type: Any = ...
    relational: bool = ...
    translate: bool = ...
    column_type: Any = ...
    column_format: str = ...
    column_cast_from: Any = ...
    _slots: Any = ...
    _sequence: Any = ...
    args: Any = ...
    _setup_done: Any = ...
    def __init__(self, string: Any = ..., **kwargs: Any) -> None: ...
    def new(self, **kwargs: Any): ...
    def __getattr__(self, name: Any): ...
    _attrs: Any = ...
    def __setattr__(self, name: Any, value: Any) -> None: ...
    def set_all_attrs(self, attrs: Any) -> None: ...
    def __delattr__(self, name: Any) -> None: ...
    def __str__(self): ...
    def __repr__(self): ...
    def setup_base(self, model: Any, name: Any) -> None: ...
    def _can_setup_from(self, field: Any): ...
    def _get_attrs(self, model: Any, name: Any): ...
    prefetch: bool = ...
    string: Any = ...
    default: Any = ...
    def _setup_attrs(self, model: Any, name: Any): ...
    def setup_full(self, model: Any) -> None: ...
    def _setup_regular_base(self, model: Any) -> None: ...
    depends: Any = ...
    def _setup_regular_full(self, model: Any): ...
    related: Any = ...
    related_field: Any = ...
    compute: Any = ...
    inverse: Any = ...
    search: Any = ...
    states: Any = ...
    required: bool = ...
    def _setup_related_full(self, model: Any) -> None: ...
    def traverse_related(self, record: Any): ...
    def _compute_related(self, records: Any) -> None: ...
    def _inverse_related(self, records: Any) -> None: ...
    def _search_related(self, records: Any, operator: Any, value: Any): ...
    _related_comodel_name: Any = ...
    _related_string: Any = ...
    _related_help: Any = ...
    _related_readonly: Any = ...
    _related_groups: Any = ...
    _related_group_operator: Any = ...
    @property
    def base_field(self): ...
    def _default_company_dependent(self, model: Any): ...
    def _compute_company_dependent(self, records: Any) -> None: ...
    def _inverse_company_dependent(self, records: Any) -> None: ...
    def _search_company_dependent(self, records: Any, operator: Any, value: Any): ...
    def resolve_deps(self, model: Any, path0: Any = ..., seen: Any = ...): ...
    recursive: bool = ...
    def setup_triggers(self, model: Any) -> None: ...
    def get_description(self, env: Any): ...
    _description_store: Any = ...
    _description_manual: Any = ...
    _description_depends: Any = ...
    _description_related: Any = ...
    _description_company_dependent: Any = ...
    _description_readonly: Any = ...
    _description_required: Any = ...
    _description_states: Any = ...
    _description_groups: Any = ...
    _description_change_default: Any = ...
    _description_deprecated: Any = ...
    @property
    def _description_searchable(self): ...
    @property
    def _description_sortable(self): ...
    def _description_string(self, env: Any): ...
    def _description_help(self, env: Any): ...
    def null(self, record: Any): ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_record(self, value: Any, record: Any): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def convert_to_write(self, value: Any, record: Any): ...
    def convert_to_onchange(self, value: Any, record: Any, names: Any): ...
    def convert_to_export(self, value: Any, record: Any): ...
    def convert_to_display_name(self, value: Any, record: Any): ...
    def update_db(self, model: Any, columns: Any): ...
    def update_db_column(self, model: Any, column: Any) -> None: ...
    def update_db_notnull(self, model: Any, column: Any) -> None: ...
    def update_db_index(self, model: Any, column: Any) -> None: ...
    def read(self, records: Any): ...
    def write(self, records: Any, value: Any, create: bool = ...): ...
    # def __get__(self, record: Any, owner: Any): ...
    def __set__(self, record: Any, value: Any) -> None: ...
    def _compute_value(self, records: Any) -> None: ...
    def compute_value(self, records: Any) -> None: ...
    def determine_value(self, record: Any) -> None: ...
    def determine_draft_value(self, record: Any): ...
    def determine_inverse(self, records: Any) -> None: ...
    def determine_domain(self, records: Any, operator: Any, value: Any): ...
    def modified_draft(self, records: Any): ...

class Boolean(Field):
    type: str = ...
    column_type: Any = ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...

class Integer(Field):
    type: str = ...
    column_type: Any = ...
    _slots: Any = ...
    _description_group_operator: Any = ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def _update(self, records: Any, value: Any) -> None: ...
    def convert_to_export(self, value: Any, record: Any): ...

class Float(Field):
    type: str = ...
    column_cast_from: Any = ...
    _slots: Any = ...
    def __init__(self, string: Any = ..., digits: Any = ..., **kwargs: Any) -> None: ...
    @property
    def column_type(self): ...
    @property
    def digits(self): ...
    _related__digits: Any = ...
    _description_digits: Any = ...
    _description_group_operator: Any = ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...

class Monetary(Field):
    type: str = ...
    column_type: Any = ...
    column_cast_from: Any = ...
    _slots: Any = ...
    def __init__(self, string: Any = ..., currency_field: Any = ..., **kwargs: Any) -> None: ...
    _related_currency_field: Any = ...
    _description_currency_field: Any = ...
    _description_group_operator: Any = ...
    currency_field: str = ...
    def _setup_regular_full(self, model: Any) -> None: ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def convert_to_write(self, value: Any, record: Any): ...

class _String(Field):
    _slots: Any = ...
    def __init__(self, string: Any = ..., **kwargs: Any) -> None: ...
    prefetch: Any = ...
    def _setup_attrs(self, model: Any, name: Any) -> None: ...
    _related_translate: Any = ...
    def _description_translate(self, env: Any): ...
    def get_trans_terms(self, value: Any): ...
    def get_trans_func(self, records: Any): ...
    def check_trans_value(self, value: Any): ...

class Char(_String):
    type: str = ...
    column_cast_from: Any = ...
    _slots: Any = ...
    @property
    def column_type(self): ...
    def update_db_column(self, model: Any, column: Any) -> None: ...
    _related_size: Any = ...
    _description_size: Any = ...
    def _setup_regular_base(self, model: Any) -> None: ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...

class Text(_String):
    type: str = ...
    column_type: Any = ...
    column_cast_from: Any = ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...

class Html(_String):
    type: str = ...
    column_type: Any = ...
    _slots: Any = ...
    def _get_attrs(self, model: Any, name: Any): ...
    _related_sanitize: Any = ...
    _related_sanitize_tags: Any = ...
    _related_sanitize_attributes: Any = ...
    _related_sanitize_style: Any = ...
    _related_strip_style: Any = ...
    _related_strip_classes: Any = ...
    _description_sanitize: Any = ...
    _description_sanitize_tags: Any = ...
    _description_sanitize_attributes: Any = ...
    _description_sanitize_style: Any = ...
    _description_strip_style: Any = ...
    _description_strip_classes: Any = ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...

class Date(Field):
    type: str = ...
    column_type: Any = ...
    column_cast_from: Any = ...
    @staticmethod
    def today(*args: Any) -> datetime.date: ...
    @staticmethod
    def context_today(record: Any, timestamp: Optional[Any] = ...) -> datetime.date: ...
    @staticmethod
    def from_string(value: Any) -> datetime.date: ...
    @staticmethod
    def to_string(value: Any): ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...

class Datetime(Field):
    type: str = ...
    column_type: Any = ...
    column_cast_from: Any = ...
    @staticmethod
    def now(*args: Any) -> datetime.datetime: ...
    @staticmethod
    def context_timestamp(record: Any, timestamp: Any) -> datetime.datetime: ...
    @staticmethod
    def from_string(value: Any) -> datetime.datetime: ...
    @staticmethod
    def to_string(value: Any) -> str: ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...
    def convert_to_display_name(self, value: Any, record: Any): ...
_BINARY = memoryview

class Binary(Field):
    type: str = ...
    _slots: Any = ...
    @property
    def column_type(self): ...
    def _get_attrs(self, model: Any, name: Any): ...
    _description_attachment: Any = ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def read(self, records: Any) -> None: ...
    def write(self, records: Any, value: Any, create: bool = ...) -> None: ...

class Selection(Field):
    type: str = ...
    _slots: Any = ...
    def __init__(self, selection: Any = ..., string: Any = ..., **kwargs: Any) -> None: ...
    @property
    def column_type(self): ...
    def _setup_regular_base(self, model: Any) -> None: ...
    selection: Any = ...
    def _setup_related_full(self, model: Any): ...
    def _setup_attrs(self, model: Any, name: Any) -> None: ...
    def _description_selection(self, env: Any): ...
    def get_values(self, env: Any): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...

class Reference(Selection):
    type: str = ...
    @property
    def column_type(self): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_record(self, value: Any, record: Any): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def convert_to_export(self, value: Any, record: Any): ...
    def convert_to_display_name(self, value: Any, record: Any): ...

class _Relational(Field):
    relational: bool = ...
    _slots: Any = ...
    comodel_name: str = ...
    def _setup_regular_base(self, model: Any) -> None: ...
    @property
    def _related_domain(self): ...
    _related_context: Any = ...
    _description_relation: Any = ...
    _description_context: Any = ...
    def _description_domain(self, env: Any): ...
    def null(self, record: Any): ...

class Many2one(_Relational):
    type: str = ...
    column_type: Any = ...
    _slots: Any = ...
    def __init__(self, comodel_name: Any = ..., string: Any = ..., **kwargs: Any) -> None: ...
    delegate: Any = ...
    def _setup_attrs(self, model: Any, name: Any) -> None: ...
    ondelete: Any = ...
    def update_db(self, model: Any, columns: Any): ...
    def update_db_column(self, model: Any, column: Any) -> None: ...
    def update_db_foreign_key(self, model: Any, column: Any) -> None: ...
    def _update(self, records: Any, value: Any) -> None: ...
    def convert_to_column(self, value: Any, record: Any, values: Optional[Any] = ...): ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_record(self, value: Any, record: Any): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def convert_to_write(self, value: Any, record: Any): ...
    def convert_to_export(self, value: Any, record: Any): ...
    def convert_to_display_name(self, value: Any, record: Any): ...
    def convert_to_onchange(self, value: Any, record: Any, names: Any): ...

class _RelationalMultiUpdate:
    __slots__: Any = ...
    record: Any = ...
    field: Any = ...
    value: Any = ...
    def __init__(self, record: Any, field: Any, value: Any) -> None: ...
    def __call__(self): ...

class _RelationalMulti(_Relational):
    _slots: Any = ...
    def _update(self, records: Any, value: Any) -> None: ...
    def convert_to_cache(self, value: Any, record: Any, validate: bool = ...): ...
    def convert_to_record(self, value: Any, record: Any): ...
    def convert_to_read(self, value: Any, record: Any, use_name_get: bool = ...): ...
    def convert_to_write(self, value: Any, record: Any): ...
    def convert_to_onchange(self, value: Any, record: Any, names: Any): ...
    def convert_to_export(self, value: Any, record: Any): ...
    def convert_to_display_name(self, value: Any, record: Any) -> None: ...
    def _compute_related(self, records: Any): ...
    def _setup_regular_full(self, model: Any) -> None: ...

class One2many(_RelationalMulti):
    type: str = ...
    _slots: Any = ...
    def __init__(self, comodel_name: Any = ..., inverse_name: Any = ..., string: Any = ..., **kwargs: Any) -> None: ...
    def _setup_regular_full(self, model: Any) -> None: ...
    _description_relation_field: Any = ...
    def convert_to_onchange(self, value: Any, record: Any, names: Any): ...
    def update_db(self, model: Any, columns: Any) -> None: ...
    def read(self, records: Any): ...
    def write(self, records: Any, value: Any, create: bool = ...) -> None: ...

class Many2many(_RelationalMulti):
    type: str = ...
    _slots: Any = ...
    def __init__(self, comodel_name: Any = ..., relation: Any = ..., column1: Any = ..., column2: Any = ..., string: Any = ..., **kwargs: Any) -> None: ...
    relation: Any = ...
    column1: Any = ...
    column2: Any = ...
    def _setup_regular_base(self, model: Any) -> None: ...
    def _setup_regular_full(self, model: Any) -> None: ...
    def update_db(self, model: Any, columns: Any): ...
    def update_db_foreign_keys(self, model: Any) -> None: ...
    def read(self, records: Any) -> None: ...
    def write(self, records: Any, value: Any, create: bool = ...) -> None: ...

class Id(Field):
    type: str = ...
    column_type: Any = ...
    _slots: Any = ...
    def update_db(self, model: Any, columns: Any) -> None: ...
    def __get__(self, record: Any, owner: Any): ...
    def __set__(self, record: Any, value: Any) -> None: ...
