# Stubs for odoo.loglevels (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

LOG_NOTSET: str
LOG_DEBUG: str
LOG_INFO: str
LOG_WARNING: str
LOG_ERROR: str
LOG_CRITICAL: str

def get_encodings(hint_encoding: str = ...) -> None: ...

text_type: Any

def ustr(value: Any, hint_encoding: str = ..., errors: str = ...): ...
def exception_to_unicode(e: Any): ...
