from typing import Any

IDENT_RE: Any

def _from_table(table, alias): ...
def _generate_table_alias(src_table_alias, link): ...

class Query:
    _cr: Any
    _tables: Any
    _joins: Any
    _where_clauses: Any
    _where_params: Any
    order: Any
    limit: Any
    offset: Any
    def __init__(self, cr, alias, table: Any | None = ...) -> None: ...
    def add_table(self, alias, table: Any | None = ...) -> None: ...
    def add_where(self, where_clause, where_params=...) -> None: ...
    def join(self, lhs_alias, lhs_column, rhs_table, rhs_column, link, extra: Any | None = ..., extra_params=...): ...
    def left_join(self, lhs_alias, lhs_column, rhs_table, rhs_column, link, extra: Any | None = ..., extra_params=...): ...
    def _join(self, kind, lhs_alias, lhs_column, rhs_table, rhs_column, link, extra: Any | None = ..., extra_params=...): ...
    def select(self, *args): ...
    def subselect(self, *args): ...
    def get_sql(self): ...
    def _result(self): ...
    def __str__(self): ...
    def __bool__(self): ...
    def __len__(self): ...
    def __iter__(self): ...
    @property
    def tables(self): ...
    @property
    def where_clause(self): ...
    @property
    def where_clause_params(self): ...
    def add_join(self, connection, implicit: bool = ..., outer: bool = ..., extra: Any | None = ..., extra_params=...): ...
