from typing import Any

class html2html:
    localcontext: Any
    etree: Any
    def __init__(self, html, localcontext) -> None: ...
    def render(self): ...
    def url_modify(self, root): ...

def parseString(node, localcontext=...): ...
