from . import security as security
from odoo.exceptions import AccessDenied as AccessDenied
from odoo.tools.translate import _ as _
from typing import Any, Optional

_logger: Any
RPC_VERSION_1: Any

def exp_login(db: Any, login: Any, password: Any): ...
def exp_authenticate(db: Any, login: Any, password: Any, user_agent_env: Any): ...
def exp_version(): ...
def exp_about(extended: bool = ...): ...
def exp_set_loglevel(loglevel: Any, logger: Optional[Any] = ...): ...
def dispatch(method: Any, params: Any): ...
