from typing import Any

_logger: Any
RPC_VERSION_1: Any

def exp_login(db, login, password): ...
def exp_authenticate(db, login, password, user_agent_env): ...
def exp_version(): ...
def exp_about(extended: bool = ...): ...
def exp_set_loglevel(loglevel, logger: Any | None = ...): ...
def dispatch(method, params): ...
