from typing import Any

self_reports: Any
self_id: int
self_id_protect: Any

def dispatch(method, params): ...
def exp_render_report(
    db, uid, object, ids, datas: Any | None = ..., context: Any | None = ...
): ...
def exp_report(
    db, uid, object, ids, datas: Any | None = ..., context: Any | None = ...
): ...
def exp_report_get(db, uid, report_id): ...
