from typing import Any

def login(db: Any, login: Any, password: Any): ...
def check(db: Any, uid: Any, passwd: Any): ...
def compute_session_token(session: Any, env: Any): ...
def check_session(session: Any, env: Any): ...
