def clear_cache(cr, uid) -> None: ...
def trg_write(uid, res_type, res_id, cr): ...
def trg_trigger(uid, res_type, res_id, cr): ...
def trg_delete(uid, res_type, res_id, cr): ...
def trg_create(uid, res_type, res_id, cr): ...
def trg_validate(uid, res_type, res_id, signal, cr): ...
def trg_redirect(uid, res_type, res_id, new_rid, cr): ...
