from typing import Any

class WorkflowInstance:
    session: Any
    record: Any
    instance: Any
    def __init__(self, session, record, values) -> None: ...
    @classmethod
    def create(cls, session, record, workflow_id): ...
    def delete(self) -> None: ...
    def validate(self, signal, force_running: bool = ...): ...
    def update(self): ...
    def _update_end(self): ...

def create(session, record, workflow_id): ...
def delete(session, record): ...
def validate(session, record, instance_id, signal, force_running: bool = ...): ...
def update(session, record, instance_id): ...
def _update_end(session, record, instance_id): ...
