from typing import Any

class WorkflowService:
    CACHE: Any
    @classmethod
    def clear_cache(cls, dbname) -> None: ...
    @classmethod
    def new(cls, cr, uid, model_name, record_id): ...
    session: Any
    record: Any
    cr: Any
    def __init__(self, session, record) -> None: ...
    def write(self) -> None: ...
    def trigger(self) -> None: ...
    def delete(self) -> None: ...
    def create(self) -> None: ...
    def validate(self, signal): ...
    def redirect(self, new_rid) -> None: ...
