from typing import Any

def str2xml(s): ...
def xml2str(s): ...
def text_get(node): ...

units: Any

def unit_get(size): ...
def tuple_int_get(node, attr_name, default: Any | None = ...): ...
def bool_get(value): ...
def attr_get(node, attrs, dict: Any | None = ...): ...
