from typing import Any

class makohtml2html:
    localcontext: Any
    html: Any
    def __init__(self, html, localcontext) -> None: ...
    def format_header(self, html): ...
    def format_footer(self, footer): ...
    def format_body(self, html): ...
    def render(self): ...

def parseNode(html, localcontext=...): ...
